name: Publish Image
on:
  - push

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the runpod-template-pytorch2 Docker image
        run: |
          docker build . --tag ghcr.io/deepghs/runpod-pytorch-conda:latest
          docker push ghcr.io/deepghs/runpod-pytorch-conda:latest

